version: '3.7'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/osrs-bot:delegated
    working_dir: /osrs-bot
    environment:
      - LOG_LEVEL=INFO